blank_issues_enabled: true
contact_links:
  - name: Code of Conduct
    url: https://github.com/tinasherobert/2026-Ideas/blob/master/CODE_OF_CONDUCT.md
    about: Community guidelines and expected behavior
